// Mocks generated by Mockito 5.4.6 from annotations
// in fundingrate/test/bybit_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fundingrate/src/data/datasources/bybit_remote_data_source.dart'
    as _i2;
import 'package:fundingrate/src/domain/entities/funding_rate.dart' as _i5;
import 'package:fundingrate/src/domain/entities/trading_pair.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [BybitRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockBybitRemoteDataSource extends _i1.Mock
    implements _i2.BybitRemoteDataSource {
  MockBybitRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.TradingPair>> getTradingPairs() =>
      (super.noSuchMethod(
            Invocation.method(#getTradingPairs, []),
            returnValue: _i3.Future<List<_i4.TradingPair>>.value(
              <_i4.TradingPair>[],
            ),
          )
          as _i3.Future<List<_i4.TradingPair>>);

  @override
  _i3.Future<List<_i5.FundingRate>> getFundingRates() =>
      (super.noSuchMethod(
            Invocation.method(#getFundingRates, []),
            returnValue: _i3.Future<List<_i5.FundingRate>>.value(
              <_i5.FundingRate>[],
            ),
          )
          as _i3.Future<List<_i5.FundingRate>>);
}
